project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "CEVE 421/521 -- Spring 2024"
  description: "Homepage for {{< var course.number >}}, {{< var course.title >}}, at Rice University, {{< var course.semester >}}."
  site-url: https://ceve-421-521.github.io/
  repo-url: https://www.github.com/ceve-421-521/ceve-421-521.github.io
  repo-actions: [edit, issue]
  open-graph: true

  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source on {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

    center: |
      **Page still under construction.**

  sidebar:
    style: docked
    align: center
    logo: _assets/logos/Rice_Logo_280_Blue.svg
    title: "CEVE 421/521"
    search: true
    tools: 
      - icon: github
        href: "{{var course.github}}"
        text: "Github Repository"
      - icon: journal-check
        href: "{{var course.canvas}}"
        text: "Canvas"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Schedule
        href: schedule.qmd
      - text: Resources
        href: resources.qmd

echo: true

format:
  # customization for HTML documents (i.e., the website)
  html:
    theme: spacelab #spacelab #simplex
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: document
    citations-hover: true
    code-annotations: hover
    code-line-numbers: true
    html-math-method: mathjax
    include-in-header: mathjax-config.html
    date-format: "ddd., MMM. D"
  
  # customization for RevealJS (i.e., the slides)
  revealjs:

    theme: _assets/sass/slides.scss
    
    # page numbering
    slide-number: c/t
    show-slide-number: all
    hash-type: number

    # page layout and transition
    center-title-slide: true
    width: 1280
    height: 720
    transition: none
    toc: false
    history: false
    menu:
        numbers: true
    scrollable: true
    preview-links: auto
    
    # code, links, and refs
    link-external-newwindow: true
    citations-hover: true
    code-annotations: below
    
    # math and code
    html-math-method: mathjax
    include-in-header: lectures/mathjax-config.html
    date-format: "ddd., MMM. D"

# references
bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

# code to use
jupyter: julia-1.10

# execution options
execute:
  freeze: auto  
  cache: true

# reveal-auto-agenda extension
filters:
  - reveal-auto-agenda

auto-agenda:
  bullets: numbered
  heading: Today